### ISSUE TITLE
udp怎么使用的?

### ISSUE THREAD

**Issue by p0we7** [Lupino/hole#1]
holed -addr=udp://x.x.x.x:1194

这条命令提示 " 2015/10/04 09:02:04 unknown network udp " 

不是说支持udp吗?

**Comment by Lupino** [comment]
我又重看了 https://golang.org/pkg/net/#Listen 是不支持的。

这下是我弄错了

**Comment by p0we7** [comment]
哎  。 蛋碎哦 。
